In [1]:
#1.Python program to add two Matrices
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = [[0,0,0],
        [0,0,0],
        [0,0,0]]
 
for i in range(len(X)):  
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]
for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [2]:
#2.	Python program to multiply two matrices
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = [[0,0,0],
        [0,0,0],
        [0,0,0]]
 
for i in range(len(X)):  
    for j in range(len(X[0])):
        result[i][j] = X[i][j] * Y[i][j]
for r in result:
    print(r)

[9, 16, 21]
[24, 25, 24]
[21, 16, 9]


In [3]:
#3.	Python program for Matrix Product
def Multiply(A,B):
    result=[ [0,0,0],[0,0,0],[0,0,0] ]
    #for rows
    for i in range(len(A)):
        #for columns
        for j in range(len(B[0])):
            #for rows of matrix B
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]

    for p in result:
        print(p)
    return 0

A = [ [1, 2, 3],[6, 7, 4], [8, 10, 11] ]
B = [[1, 5, 3],[2, 6, 5], [7, 4, 9] ]

print("Result: ")
Multiply(A,B)

Result: 
[26, 29, 40]
[48, 88, 89]
[105, 144, 173]


0

In [9]:
#4.	Adding and Subtracting Matrices in Python
import numpy as np
  
A = np.array([[1, 2], [3, 4]])
  
B = np.array([[4, 5], [6, 7]])
  

# subtracting two matrix
print("Subtraction of two matrix")
print(np.subtract(A, B))

# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Subtraction of two matrix
[[-3 -3]
 [-3 -3]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [10]:
#5.Transpose a matrix in Single line in Python
import numpy 
matrix=[[1,2,3],[4,5,6]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))

[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


In [13]:
#6.Python | Matrix creation of n*n
n = int(input("Enter number:"))
matrix = [list(range(1 + n * i, 1 + n * (i + 1))) for i in range(n)]
print("The created matrix of {} * {}: ".format(n,n))
for m in matrix:
    print(m)

Enter number:3
The created matrix of 3 * 3: 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [16]:
#7.Python | Get Kth Column of Matrix
test_list = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
  
print("The original list is : " + str(test_list))
  
K = int(input("Enter kth value :"))
  
# Get Kth Column of Matrix
res = [sub[K] for sub in test_list]
  
print("The Kth column of matrix is : " + str(res))

The original list is : [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
Enter kth value :2
The Kth column of matrix is : [6, 10, 5]


In [17]:
#8.Python – Vertical Concatenation in Matrix
test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]
  
print("The original list : " + str(test_list))
  
res = []
N = 0
while N != len(test_list):
    temp = ''
    for idx in test_list:
          
        # checking for valid index / column
        try: temp = temp + idx[N]
        except IndexError: pass
    res.append(temp)
    N = N + 1
    
res = [ele for ele in res if ele]
  
# printing result 
print("List after column Concatenation : " + str(res))

The original list : [['Gfg', 'good'], ['is', 'for'], ['Best']]
List after column Concatenation : ['GfgisBest', 'goodfor']


In [23]:
#9.Python program to check if a string is palindrome or not
def isPalindrome(s):
    return s == s[::-1]
 
s = "malayalam"
ans = isPalindrome(s)
 
if ans:
    print("Yes the entered string is palindrome")
else:
    print("No the entered string is not palindrome")

Yes the entered string is palindrome


In [22]:
#10.Python program to check whether the string is Symmetrical or Palindrome


def palindrome(a):

    mid = (len(a)-1)//2
    start = 0
    last = len(a)-1
    flag = 0


    while(start <= mid):


        if (a[start]== a[last]):

            start += 1
            last -= 1

        else:
            flag = 1
            break;


    if flag == 0:
        print("The entered string is palindrome")
    else:
        print("The entered string is not palindrome")


def symmetry(a):

    n = len(a)
    flag = 0


    if n%2:
        mid = n//2 +1
    else:
        mid = n//2

    start1 = 0
    start2 = mid

    while(start1 < mid and start2 < n):

        if (a[start1]== a[start2]):
            start1 = start1 + 1
            start2 = start2 + 1
        else:
            flag = 1
            break

    if flag == 0:
        print("The entered string is symmetrical")
    else:
        print("The entered string is not symmetrical")

string = 'amaama'
palindrome(string)
symmetry(string)


The entered string is palindrome
The entered string is symmetrical
